# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackTheJorney2018' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackTheJorney2018
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'HackTheJorney2018Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HackTheJorney2018UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
